Repository Zsezsu/terraforming-mars, pull requests merged in 2022-06, with the labels that each got.

#49 Fix user number indicator on league cards
  queries/select_queries.py
Labels: bug

#65 Database ares
  api.py
  database/(1)_db_schema.sql
  database/(2)_insert_images.sql
  database/(3)_2022.06.29-16:00_insert_game_type.sql
  database/(4)_2022.06.29-16:57_ares_corporations.sql
  database/(5)_2022.06.30-17:30_ares_expedition_point_system.sql
  database/insert_players.sql
  database/insert_test_values.sql
  database/planning/game_type_planning.png
  database/planning/terraforming_mars_game_type.drawio
  helper.py
  queries/insert_queries.py
  queries/select_queries.py
  server.py
  static/js/addLeague.js
  static/js/data/dataHandler.js
  static/js/filter.js
  static/js/roundDetails.js
  static/js/roundInitGame.js
  static/js/roundStarted.js
  static/style/cards.css
  templates/my_leagues.html
  templates/round_phase_init_game.html
  templates/round_phase_started.html
Labels: bug, enhancement

#66 Feature profile page design
  api.py
  queries/select_queries.py
  queries/update_queries.py
  server.py
  static/js/components/slideshow.js
  static/js/data/dataHandler.js
  static/js/profile.js
  static/js/profileSlideshow.js
  static/style/global.css
  static/style/profile.css
  templates/dashboard.html
  templates/layout/layout.html
  templates/profile.html
  templates/round_phase_started.html
Labels: enhancement
